#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Mar 24 17:37:14 GMT 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 888ad046b2df4393bb0c18ee2e71393b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot vi_sys_top_level_behav xil_defaultlib.vi_sys_top_level -log elaborate.log"
xelab -wto 888ad046b2df4393bb0c18ee2e71393b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot vi_sys_top_level_behav xil_defaultlib.vi_sys_top_level -log elaborate.log

